server:
  port: 8081



dubbo:
  application:
    #服务应用的名称
    name: provider-server
    #注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
    #哪些服务要被注册

  scan:
    base-packages: com.cuisf.service
